apiVersion: v1
kind: Pod
metadata:
  labels:
    app : nginx
  name: nginx
  namespace: dev
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
