apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 80