apiVersion: v1
data:
  insecure: dHJ1ZQ==
  project: QXJnby1UZXN0
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL3Zpa3JhbXBydXRodmk1L0s4cy1BcmdvVGVzdC5naXQ=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  creationTimestamp: "2026-02-26T07:06:01Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-75021767
  namespace: default
  resourceVersion: "194793"
  uid: d7a5538b-495b-4100-81fc-716a07ef3ae2
type: Opaque
